image: ubuntu:latest

before_script:
  - sed -i~orig -e 's/# deb-src/deb-src/' /etc/apt/sources.list
  - apt-get update -qq && apt-get build-dep -qq qtcreator && apt-get install -qq cmake git

build:
  script:
    - mkdir build && cd build/
    - cmake ..
    - make

test:
  script:
    - cd build/ && make test

