image: ubuntu:latest

stages:
  - build
  - test

before_script:
  - sed -i~orig -e 's/# deb-src/deb-src/' /etc/apt/sources.list
  - apt-get update -qq && apt-get build-dep -qq qtcreator && apt-get install -qq cmake git

compile:
  stage: build
  artifacts:
    paths:
      - build
  script:
    - mkdir build && cd build/
    - cmake ..
    - make

test:
  stage: test
  dependencies:
    - compile
  script:
    - ls
    - pwd
    - cd build
    - make test
